import { VoteRepository } from "../../domain/vote/vote.repository";
import { VoteValue } from "../../domain/vote/vote.value";
import { TimezoneConverter } from "../../infrastructure/utils/TimezoneConverter";

export class VoteUseCase {
    constructor(
        private readonly voteRepository: VoteRepository,
    ) {
        this.getVotes = this.getVotes.bind(this);
        this.getDetailVote = this.getDetailVote.bind(this);
        this.createVote = this.createVote.bind(this);
        this.updateVote = this.updateVote.bind(this);
        this.deleteVote = this.deleteVote.bind(this);
    }

    public async getVotes(cmp_uuid: string, cla_uuid: string, ten_uuid: string) {
        try {
            const votes = await this.voteRepository.getVotes(cmp_uuid, cla_uuid, ten_uuid);
            if (!votes) {
                throw new Error('No hay votos.');
            }
            return votes.map(vote => ({
                cmp_uuid: vote.cmp_uuid,
                cla_uuid: vote.cla_uuid,
                ten_uuid: vote.ten_uuid,
                usr_uuid: vote.usr_uuid,
                vto_uuid: vote.vto_uuid,
                tenopt_uuid: vote.tenopt_uuid,
                vto_createdat: TimezoneConverter.toIsoStringInTimezone(vote.vto_createdat, 'America/Buenos_Aires')
            }));
        } catch (error: any) {
            console.error('Error en getVotes (use case):', error.message);
            throw error;
        }
    }

    public async getDetailVote(cmp_uuid: string, cla_uuid: string, ten_uuid: string, usr_uuid: string, vto_uuid: string) {
        try {
            const vote = await this.voteRepository.findVoteById(cmp_uuid, cla_uuid, ten_uuid, usr_uuid, vto_uuid);
            if (!vote) {
                throw new Error(`No hay voto con ID: ${vto_uuid}`);
            }
            return {
                cmp_uuid: vote.cmp_uuid,
                cla_uuid: vote.cla_uuid,
                ten_uuid: vote.ten_uuid,
                usr_uuid: vote.usr_uuid,
                vto_uuid: vote.vto_uuid,
                tenopt_uuid: vote.tenopt_uuid,
                vto_createdat: TimezoneConverter.toIsoStringInTimezone(vote.vto_createdat, 'America/Buenos_Aires')
            };
        } catch (error: any) {
            console.error('Error en getDetailVote (use case):', error.message);
            throw error;
        }
    }

    public async createVote({ cmp_uuid, cla_uuid, ten_uuid, usr_uuid, vto_uuid, tenopt_uuid }: { cmp_uuid: string, cla_uuid: string, ten_uuid: string, usr_uuid: string, vto_uuid?: string, tenopt_uuid: string }) {
        try {
            // Verificar si el usuario ya votó en esta licitación
            const existingVotes = await this.voteRepository.getVotes(cmp_uuid, cla_uuid, ten_uuid);
            const alreadyVoted = existingVotes?.some(v => v.usr_uuid === usr_uuid);
            if (alreadyVoted) {
                throw new Error('Ya has registrado tu voto en esta licitación.');
            }

            // Note: vto_uuid is optional here as it will be generated by VoteValue constructor.
            // We pass vto_uuid as undefined if not provided, but we cast it just to satisfy the parameter list if typescript requires it.
            const voteValue = new VoteValue({ cmp_uuid, cla_uuid, ten_uuid, usr_uuid, vto_uuid: vto_uuid as any, tenopt_uuid });
            const voteCreated = await this.voteRepository.createVote(voteValue);
            if (!voteCreated) {
                throw new Error('No se pudo registrar el voto.');
            }
            return {
                cmp_uuid: voteCreated.cmp_uuid,
                cla_uuid: voteCreated.cla_uuid,
                ten_uuid: voteCreated.ten_uuid,
                usr_uuid: voteCreated.usr_uuid,
                vto_uuid: voteCreated.vto_uuid,
                tenopt_uuid: voteCreated.tenopt_uuid,
                vto_createdat: TimezoneConverter.toIsoStringInTimezone(voteCreated.vto_createdat, 'America/Buenos_Aires')
            };
        } catch (error: any) {
            console.error('Error en createVote (use case):', error.message);
            throw error;
        }
    }

    public async updateVote(cmp_uuid: string, cla_uuid: string, ten_uuid: string, usr_uuid: string, vto_uuid: string, { tenopt_uuid }: { tenopt_uuid: string }) {
        try {
            const voteUpdated = await this.voteRepository.updateVote(cmp_uuid, cla_uuid, ten_uuid, usr_uuid, vto_uuid, { tenopt_uuid });
            if (!voteUpdated) {
                throw new Error('No se pudo actualizar el voto.');
            }
            return {
                cmp_uuid: voteUpdated.cmp_uuid,
                cla_uuid: voteUpdated.cla_uuid,
                ten_uuid: voteUpdated.ten_uuid,
                usr_uuid: voteUpdated.usr_uuid,
                vto_uuid: voteUpdated.vto_uuid,
                tenopt_uuid: voteUpdated.tenopt_uuid,
                vto_createdat: TimezoneConverter.toIsoStringInTimezone(voteUpdated.vto_createdat, 'America/Buenos_Aires')
            };
        } catch (error: any) {
            console.error('Error en updateVote (use case):', error.message);
            throw error;
        }
    }

    public async deleteVote(cmp_uuid: string, cla_uuid: string, ten_uuid: string, usr_uuid: string, vto_uuid: string) {
        try {
            const voteDeleted = await this.voteRepository.deleteVote(cmp_uuid, cla_uuid, ten_uuid, usr_uuid, vto_uuid);
            if (!voteDeleted) {
                throw new Error('No se pudo eliminar el voto.');
            }
            return {
                cmp_uuid: voteDeleted.cmp_uuid,
                cla_uuid: voteDeleted.cla_uuid,
                ten_uuid: voteDeleted.ten_uuid,
                usr_uuid: voteDeleted.usr_uuid,
                vto_uuid: voteDeleted.vto_uuid,
                tenopt_uuid: voteDeleted.tenopt_uuid,
                vto_createdat: TimezoneConverter.toIsoStringInTimezone(voteDeleted.vto_createdat, 'America/Buenos_Aires')
            };
        } catch (error: any) {
            console.error('Error en deleteVote (use case):', error.message);
            throw error;
        }
    }
}
