import { FeeRepository } from "../../domain/fee/fee.repository";
import { FeeValue } from "../../domain/fee/fee.value";
import { TimezoneConverter } from "../../infrastructure/utils/TimezoneConverter";

export class FeeUseCase {
    constructor(
        private readonly feeRepository: FeeRepository,
    ) {
        this.getFees = this.getFees.bind(this);
        this.getDetailFee = this.getDetailFee.bind(this);
        this.createFee = this.createFee.bind(this);
        this.updateFee = this.updateFee.bind(this);
        this.deleteFee = this.deleteFee.bind(this);
    }

    public async getFees(cmp_uuid: string, usr_uuid?: string, uni_uuid?: string, usruni_uuid?: string, filters?: any) {
        try {
            const fees = await this.feeRepository.getFees(cmp_uuid, usr_uuid, uni_uuid, usruni_uuid, filters);
            if (!fees) {
                throw new Error('No hay expensas.');
            }
            return fees.map((fee: any) => ({
                cmp_uuid: fee.cmp_uuid,
                usr_uuid: fee.usr_uuid,
                uni_uuid: fee.uni_uuid,
                usruni_uuid: fee.usruni_uuid,
                fee_uuid: fee.fee_uuid,
                fee_period: fee.fee_period,
                fee_amount: Number(fee.fee_amount),
                fee_duedate: TimezoneConverter.toIsoStringInTimezone(fee.fee_duedate, 'America/Buenos_Aires'),
                fee_status: fee.fee_status,
                fee_createdat: TimezoneConverter.toIsoStringInTimezone(fee.fee_createdat, 'America/Buenos_Aires'),
                usr: fee.usr ? {
                    usr_uuid: fee.usr.usr_uuid,
                    usr_name: fee.usr.usr_name,
                    usr_surname: fee.usr.usr_surname,
                    usr_email: fee.usr.usr_email
                } : undefined,
                unit: fee.unit ? {
                    uni_uuid: fee.unit.uni_uuid,
                    uni_code: fee.unit.uni_code,
                    uni_category: fee.unit.uni_category
                } : undefined
            }));
        } catch (error: any) {
            console.error('Error en getFees (use case):', error.message);
            throw error;
        }
    }

    public async getDetailFee(cmp_uuid: string, usr_uuid: string, uni_uuid: string, usruni_uuid: string, fee_uuid: string) {
        try {
            const fee = await this.feeRepository.findFeeById(cmp_uuid, usr_uuid, uni_uuid, usruni_uuid, fee_uuid);
            if (!fee) {
                throw new Error(`No hay expensa con ID: ${fee_uuid}`);
            }
            return {
                cmp_uuid: fee.cmp_uuid,
                usr_uuid: fee.usr_uuid,
                uni_uuid: fee.uni_uuid,
                usruni_uuid: fee.usruni_uuid,
                fee_uuid: fee.fee_uuid,
                fee_period: fee.fee_period,
                fee_amount: Number(fee.fee_amount),
                fee_duedate: TimezoneConverter.toIsoStringInTimezone(fee.fee_duedate, 'America/Buenos_Aires'),
                fee_status: fee.fee_status,
                fee_createdat: TimezoneConverter.toIsoStringInTimezone(fee.fee_createdat, 'America/Buenos_Aires')
            };
        } catch (error: any) {
            console.error('Error en getDetailFee (use case):', error.message);
            throw error;
        }
    }

    public async createFee(body: any) {
        try {
            // fee_uuid will be generated by constructor, but we specify body arguments
            const feeValue = new FeeValue(body);
            const feeCreated = await this.feeRepository.createFee(feeValue);
            if (!feeCreated) {
                throw new Error('No se pudo registrar la expensa.');
            }
            return {
                cmp_uuid: feeCreated.cmp_uuid,
                usr_uuid: feeCreated.usr_uuid,
                uni_uuid: feeCreated.uni_uuid,
                usruni_uuid: feeCreated.usruni_uuid,
                fee_uuid: feeCreated.fee_uuid,
                fee_period: feeCreated.fee_period,
                fee_amount: Number(feeCreated.fee_amount),
                fee_duedate: TimezoneConverter.toIsoStringInTimezone(feeCreated.fee_duedate, 'America/Buenos_Aires'),
                fee_status: feeCreated.fee_status,
                fee_createdat: TimezoneConverter.toIsoStringInTimezone(feeCreated.fee_createdat, 'America/Buenos_Aires')
            };
        } catch (error: any) {
            console.error('Error en createFee (use case):', error.message);
            throw error;
        }
    }

    public async updateFee(cmp_uuid: string, usr_uuid: string, uni_uuid: string, usruni_uuid: string, fee_uuid: string, body: any) {
        try {
            const feeUpdated = await this.feeRepository.updateFee(cmp_uuid, usr_uuid, uni_uuid, usruni_uuid, fee_uuid, body);
            if (!feeUpdated) {
                throw new Error('No se pudo actualizar la expensa.');
            }
            return {
                cmp_uuid: feeUpdated.cmp_uuid,
                usr_uuid: feeUpdated.usr_uuid,
                uni_uuid: feeUpdated.uni_uuid,
                usruni_uuid: feeUpdated.usruni_uuid,
                fee_uuid: feeUpdated.fee_uuid,
                fee_period: feeUpdated.fee_period,
                fee_amount: Number(feeUpdated.fee_amount),
                fee_duedate: TimezoneConverter.toIsoStringInTimezone(feeUpdated.fee_duedate, 'America/Buenos_Aires'),
                fee_status: feeUpdated.fee_status,
                fee_createdat: TimezoneConverter.toIsoStringInTimezone(feeUpdated.fee_createdat, 'America/Buenos_Aires')
            };
        } catch (error: any) {
            console.error('Error en updateFee (use case):', error.message);
            throw error;
        }
    }

    public async deleteFee(cmp_uuid: string, usr_uuid: string, uni_uuid: string, usruni_uuid: string, fee_uuid: string) {
        try {
            const feeDeleted = await this.feeRepository.deleteFee(cmp_uuid, usr_uuid, uni_uuid, usruni_uuid, fee_uuid);
            if (!feeDeleted) {
                throw new Error('No se pudo eliminar la expensa.');
            }
            return {
                cmp_uuid: feeDeleted.cmp_uuid,
                usr_uuid: feeDeleted.usr_uuid,
                uni_uuid: feeDeleted.uni_uuid,
                usruni_uuid: feeDeleted.usruni_uuid,
                fee_uuid: feeDeleted.fee_uuid,
                fee_period: feeDeleted.fee_period,
                fee_amount: Number(feeDeleted.fee_amount),
                fee_duedate: TimezoneConverter.toIsoStringInTimezone(feeDeleted.fee_duedate, 'America/Buenos_Aires'),
                fee_status: feeDeleted.fee_status,
                fee_createdat: TimezoneConverter.toIsoStringInTimezone(feeDeleted.fee_createdat, 'America/Buenos_Aires')
            };
        } catch (error: any) {
            console.error('Error en deleteFee (use case):', error.message);
            throw error;
        }
    }
}
